version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python:
    image: python:3.12.8
    container_name: python
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash

volumes:
  pgdata:
